apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: applications
  namespace: argocd 
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/shuffleSoftware/app-configs' 
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: cluster-addons
  namespace: argocd 
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - 'https://github.com/shuffleSoftware/cluster-addons' 
