apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addon-appset
  namespace: argocd
spec: 
  generators:
    - git:
        repoURL: https://github.com/{{ .Values.gitHubAccount }}/cluster-addons
        revision: main
        files:
          - path: "cluster-addons/*/{{.Values.env }}/values.yaml"
        values:
          env: "{{.Values.env }}"
  syncPolicy:
    preserveResourcesOnDeletion: true
  template:
    metadata:
      name: '{{ "{{path[1]}}" }}'
    spec:
      project: cluster-addons
      source:
        repoURL: https://github.com/{{ .Values.gitHubAccount }}/cluster-addons
        targetRevision: main
        path: '{{ "{{path}}" }}'
        helm:
          valueFiles:
          - ../values.default.yaml
          - values.yaml
          parameters:
          - name: "custom_github_url"
            value: {{ .Values.custom_github_url }}
          - name: "custom_github_username"
            value: {{ .Values.custom_github_username }}
          - name: "custom_github_password"
            value: {{ .Values.custom_github_password }}
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ "{{config.namespace}}" }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true      
        automated:
          prune: true
          selfHeal: true